import {
  Brain,
  LineChart,
  Shield,
  Bell,
  Settings,
  Radio,
  ClipboardCheck,
} from "lucide-react";
import type { Solution, Industry, Stat } from "@/types";

export const COMPANY = {
  name: "VASP Systemic",
  tagline: "Building India's Intelligent Railway Operations Ecosystem",
  email: "vaspsystemic@gmail.com",
  phone: "+91 8446636550",
  address: "Prakash Tower, YN Road, Race Course Road, Tukoganj, Indore, Madhya Pradesh 452001",
} as const;

export const NAV_LINKS = [
  { label: "Home", href: "/" },
  { label: "About Us", href: "/about" },
  { label: "Solutions", href: "/solutions" },
  { label: "Products", href: "/products" },
  { label: "Industries", href: "/industries" },
  { label: "Technology", href: "/technology" },
  { label: "Case Studies", href: "/case-studies" },
  { label: "Blog", href: "/blog" },
  { label: "Careers", href: "/careers" },
  { label: "Contact", href: "/contact" },
] as const;

export const CORE_STRENGTHS = [
  { icon: Brain, title: "AI Powered Intelligence", description: "Advanced machine learning algorithms for predictive analytics and intelligent decision-making in railway operations." },
  { icon: Radio, title: "IoT Monitoring", description: "Real-time sensor networks enabling comprehensive monitoring of railway assets and infrastructure." },
  { icon: LineChart, title: "Predictive Maintenance", description: "AI-driven maintenance scheduling that reduces downtime and extends asset lifecycle." },
  { icon: Shield, title: "Safety Systems", description: "Enterprise-grade safety solutions ensuring compliance with railway safety standards." },
  { icon: Bell, title: "Real-Time Analytics", description: "Instant data processing and visualization for informed operational decisions." },
  { icon: Settings, title: "Operational Excellence", description: "Integrated solutions for streamlined railway operations and resource optimization." },
];

export const SOLUTIONS: Solution[] = [
  {
    title: "Railway IoT Platform",
    slug: "railway-iot-platform",
    description: "Comprehensive IoT platform connecting railway assets for real-time monitoring and control.",
    overview: "Our Railway IoT Platform serves as the digital backbone for modern railway operations, connecting thousands of sensors across trains, tracks, and stations into a unified monitoring ecosystem.",
    features: ["Real-time asset tracking", "Multi-protocol support", "Edge computing capabilities", "Scalable architecture", "Secure data transmission"],
    benefits: ["Reduced operational costs", "Improved asset utilization", "Enhanced safety compliance", "Data-driven decision making", "Centralized control"],
    useCases: ["Train location tracking", "Asset health monitoring", "Energy management", "Passenger information systems"],
    architecture: "Cloud-native microservices architecture with edge computing nodes at railway stations and onboard trains.",
    impact: "30% reduction in operational downtime and 25% improvement in asset utilization.",
    icon: "Cpu",
  },
  {
    title: "Coach Monitoring System",
    slug: "coach-monitoring-system",
    description: "Intelligent coach monitoring for passenger comfort, safety, and operational efficiency.",
    overview: "Advanced coach monitoring solution providing real-time visibility into coach conditions, passenger safety, and environmental parameters.",
    features: ["Environmental monitoring", "Passenger counting", "HVAC control", "Lighting automation", "Emergency detection"],
    benefits: ["Enhanced passenger comfort", "Reduced energy costs", "Improved safety", "Regulatory compliance", "Operational insights"],
    useCases: ["Passenger coach monitoring", "Luxury coach management", "Emergency response coordination"],
    architecture: "Distributed sensor network with central analytics platform and mobile monitoring dashboards.",
    impact: "40% improvement in passenger satisfaction and 20% reduction in energy consumption.",
    icon: "Train",
  },
  {
    title: "Asset Monitoring",
    slug: "asset-monitoring",
    description: "Comprehensive asset monitoring and management for railway infrastructure.",
    overview: "End-to-end asset monitoring solution that tracks the health, location, and performance of all railway assets in real-time.",
    features: ["Asset lifecycle tracking", "Condition-based monitoring", "Geofencing alerts", "Maintenance scheduling", "Performance analytics"],
    benefits: ["Extended asset life", "Reduced maintenance costs", "Improved reliability", "Compliance tracking", "Optimized inventory"],
    useCases: ["Track and signal monitoring", "Rolling stock management", "Station infrastructure", "Power equipment tracking"],
    architecture: "IoT sensor mesh connected to cloud analytics platform with predictive maintenance engine.",
    impact: "35% reduction in maintenance costs and 50% fewer unplanned breakdowns.",
    icon: "Cog",
  },
  {
    title: "Predictive Maintenance",
    slug: "predictive-maintenance",
    description: "AI-driven predictive maintenance to prevent failures before they occur.",
    overview: "Leverage machine learning algorithms to predict equipment failures and schedule maintenance proactively, minimizing disruption.",
    features: ["Failure prediction", "Remaining useful life estimation", "Maintenance optimization", "Root cause analysis", "Automated reporting"],
    benefits: ["Zero unplanned downtime", "Reduced maintenance costs", "Extended equipment life", "Improved safety", "Optimized spare parts"],
    useCases: ["Locomotive engine health", "Track defect prediction", "Signal system monitoring", "Pantograph inspection"],
    architecture: "ML models trained on historical data with real-time sensor feeds and automated alerting system.",
    impact: "60% reduction in unplanned failures and 45% decrease in maintenance expenditure.",
    icon: "Brain",
  },
  {
    title: "Safety Intelligence System",
    slug: "safety-intelligence-system",
    description: "AI-powered safety system for real-time hazard detection and prevention.",
    overview: "Comprehensive safety intelligence platform that uses AI and computer vision to detect, predict, and prevent safety incidents in railway operations.",
    features: ["Computer vision monitoring", "Hazard detection alerts", "Incident prediction", "Safety compliance", "Automated reporting"],
    benefits: ["Reduced accident rates", "Regulatory compliance", "Improved safety culture", "Real-time alerts", "Data-driven safety insights"],
    useCases: ["Level crossing safety", "Platform edge detection", "Worker safety monitoring", "Trespassing detection"],
    architecture: "Edge AI cameras and sensors feeding into a centralized safety analytics and alerting platform.",
    impact: "70% reduction in safety incidents and 90% faster incident response times.",
    icon: "Shield",
  },
  {
    title: "MCC Platform",
    slug: "mcc-platform",
    description: "A centralized digital platform that enables real-time monitoring, workforce management, cleaning compliance, audit readiness, contractor performance tracking, passenger feedback collection, and analytics-driven decision making across railway operations.",
    overview: "The MCC Platform enables Indian Railways and railway contractors to digitize operational workflows, improve accountability, automate compliance processes, and generate audit-ready reports through a centralized digital ecosystem.",
    features: [
      "Digital Workflow Automation",
      "Real-Time Monitoring",
      "Role-Based Access Control",
      "AI-Powered Scoring",
      "Attendance Verification",
      "Complaint Management",
      "Passenger Feedback Collection",
      "Contractor Performance Tracking",
      "Audit-Ready Reporting",
      "Executive Dashboards",
    ],
    benefits: [
      "Reduced Manual Work",
      "Improved Transparency",
      "Faster Compliance Audits",
      "Better Workforce Accountability",
      "Improved Service Quality",
      "Higher Operational Efficiency",
      "Enhanced Passenger Satisfaction",
    ],
    useCases: [
      "Indian Railways Operations",
      "Metro Rail Maintenance",
      "Cleaning Contractor Management",
      "Railway Maintenance Organizations",
      "Government Infrastructure Projects",
    ],
    architecture: "Enterprise multi-tier architecture: Field Workforce → Contractor Supervisors → Railway Supervisors → Division Administrators → Central MCC Platform → Analytics & Reporting Layer, with secure data flow across all tiers.",
    impact: "Reduced manual paperwork, improved transparency, faster compliance audits, better workforce accountability, and enhanced passenger satisfaction across railway cleaning operations.",
    icon: "ClipboardCheck",
  },
  {
    title: "Real-Time Alerts",
    slug: "real-time-alerts",
    description: "Instant notification system for critical railway events and anomalies.",
    overview: "Real-time alerting system that notifies relevant stakeholders instantly about critical events, anomalies, and system status changes.",
    features: ["Multi-channel alerts", "Severity-based routing", "Escalation workflows", "Alert analytics", "Integration APIs"],
    benefits: ["Faster response times", "Reduced downtime", "Improved situational awareness", "Automated workflows", "Comprehensive audit trails"],
    useCases: ["Emergency response coordination", "System failure alerts", "Security breach detection", "Maintenance triggers"],
    architecture: "Event-driven notification engine with SMS, email, push, and dashboard alerting channels.",
    impact: "80% faster incident response and 95% alert delivery reliability.",
    icon: "Bell",
  },
  {
    title: "AI Analytics Platform",
    slug: "ai-analytics-platform",
    description: "Advanced analytics platform for deep insights into railway operations.",
    overview: "Enterprise AI analytics platform that processes vast amounts of railway data to deliver actionable insights and business intelligence.",
    features: ["Predictive analytics", "Prescriptive analytics", "Data visualization", "Custom dashboards", "Report generation"],
    benefits: ["Data-driven strategy", "Operational optimization", "Revenue growth insights", "Cost reduction", "Competitive advantage"],
    useCases: ["Passenger flow analysis", "Revenue optimization", "Route planning", "Capacity management"],
    architecture: "Big data pipeline with ML processing layer and interactive visualization dashboards.",
    impact: "25% revenue improvement and 35% better resource allocation.",
    icon: "BarChart3",
  },
  {
    title: "Operations Dashboard",
    slug: "operations-dashboard",
    description: "Unified command center for end-to-end railway operations management.",
    overview: "Centralized operations dashboard providing complete visibility and control over all railway operations from a single interface.",
    features: ["Live operations view", "KPI tracking", "Resource management", "Incident management", "Performance reporting"],
    benefits: ["Complete operational visibility", "Improved coordination", "Faster decision making", "Resource optimization", "Performance tracking"],
    useCases: ["Control center operations", "Fleet management", "Station operations", "Emergency management"],
    architecture: "Real-time data aggregation platform with customizable widgets and role-based access control.",
    impact: "40% improvement in operational efficiency and 50% faster decision-making.",
    icon: "LayoutDashboard",
  },
];

export const INDUSTRIES: Industry[] = [
  {
    name: "Indian Railways",
    slug: "indian-railways",
    description: "Comprehensive digital transformation solutions for Indian Railways.",
    challenges: ["Aging infrastructure", "High operational costs", "Safety concerns", "Capacity constraints", "Maintenance backlog"],
    solution: "End-to-end IoT and AI platform for real-time monitoring, predictive maintenance, and operational optimization tailored for Indian Railways.",
    benefits: ["Modernized operations", "Enhanced safety", "Reduced costs", "Improved punctuality", "Better passenger experience"],
    roi: "35% reduction in operational costs, 50% fewer delays, 60% improvement in safety metrics.",
    icon: "Train",
  },
  {
    name: "Metro Rail",
    slug: "metro-rail",
    description: "Smart solutions for modern metro rail systems.",
    challenges: ["High frequency operations", "Passenger safety", "Energy management", "System integration", "Regulatory compliance"],
    solution: "Integrated metro management platform with AI-powered operations, safety systems, and passenger information solutions.",
    benefits: ["Automated operations", "Enhanced safety", "Energy optimization", "Seamless integration", "Regulatory compliance"],
    roi: "25% energy savings, 40% operational efficiency gain, 99% system availability.",
    icon: "Building2",
  },
  {
    name: "Freight Rail",
    slug: "freight-rail",
    description: "Digital solutions for efficient freight rail operations.",
    challenges: ["Asset tracking", "Cargo security", "Schedule optimization", "Fuel efficiency", "Maintenance planning"],
    solution: "Comprehensive freight management platform with real-time tracking, predictive analytics, and automated scheduling.",
    benefits: ["Improved asset utilization", "Cargo security", "Optimized schedules", "Fuel savings", "Reduced downtime"],
    roi: "20% increase in asset utilization, 15% fuel savings, 30% reduction in transit times.",
    icon: "Warehouse",
  },
  {
    name: "Industrial IoT",
    slug: "industrial-iot",
    description: "Enterprise IoT solutions for industrial applications beyond railways.",
    challenges: ["Data silos", "Legacy integration", "Security concerns", "Scalability", "Real-time processing"],
    solution: "Scalable industrial IoT platform with edge computing, secure connectivity, and advanced analytics for diverse industrial applications.",
    benefits: ["Connected operations", "Data unification", "Enhanced security", "Scalable architecture", "Real-time insights"],
    roi: "40% improvement in operational efficiency, 50% faster data processing, 99.9% data reliability.",
    icon: "Factory",
  },
  {
    name: "Smart Infrastructure",
    slug: "smart-infrastructure",
    description: "Intelligent infrastructure monitoring and management solutions.",
    challenges: ["Infrastructure aging", "Monitoring gaps", "Maintenance costs", "Safety compliance", "Resource optimization"],
    solution: "Smart infrastructure platform with continuous monitoring, predictive analytics, and automated maintenance workflows.",
    benefits: ["Extended infrastructure life", "Reduced costs", "Improved safety", "Automated compliance", "Resource optimization"],
    roi: "45% reduction in infrastructure maintenance costs, 70% fewer structural failures, 3x asset life extension.",
    icon: "Network",
  },
];

export const STATS: Stat[] = [
  { value: 500, suffix: "+", label: "Railway Assets Monitored" },
  { value: 98, suffix: "%", label: "System Uptime" },
  { value: 50, suffix: "+", label: "Enterprise Clients" },
  { value: 99.9, suffix: "%", label: "Data Accuracy" },
];

export const BLOG_CATEGORIES = [
  "Railway Technology",
  "Artificial Intelligence",
  "Industrial IoT",
  "Safety Engineering",
  "Predictive Maintenance",
  "Infrastructure Technology",
];

export const DEPARTMENTS = [
  "Engineering",
  "Product",
  "Research & Development",
  "Sales & Business Development",
  "Marketing",
  "Operations",
  "Human Resources",
  "Finance",
];
